name: plur_engine
description: The engine behind PlurIdle.
version: 0.0.1
repository: https://github.com/RainbowSprinkles-SugarSoft/PlurEngine

environment:
  sdk: ^3.5.1

publish_to: 'none'

dependencies:
  reliable_interval_timer: ^1.0.2
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
